### ISSUE TITLE
[Question] 19 dependencies seems excessive. Are all really needed?

### ISSUE THREAD

**Issue by chipweinberger** [boskokg/flutter_blue_plus#236]
Flutter Blue Plus uses 19 dependencies. **Edit**: actually I misunderstood the output of `pub add`, Im not sure the real number, including child dependencies.

As we all know, more dependencies == things break more often == more maintenance == more work!

Can you provide guidance on what these are used for? It would be great to get rid of any unneeded dependencies.

I would be happy to help.

```
dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.1
  protobuf: ^2.0.1
  rxdart: ^0.27.5
  collection: ^1.15.0
  meta: ^1.7.0

```
```
flutter pub add flutter_blue_plus
Resolving dependencies...
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
+ convert 3.1.1
+ fixnum 1.1.0
+ flutter_blue_plus 1.4.0
  intl 0.17.0 (0.18.0 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.15 available)
  material_color_utilities 0.2.0 (0.3.0 available)
  meta 1.8.0 (1.9.1 available)
  path 1.8.2 (1.8.3 available)
  path_provider_android 2.0.24 (2.0.25 available)
  path_provider_foundation 2.2.1 (2.2.2 available)
+ protobuf 2.1.0
+ rxdart 0.27.7
  source_span 1.9.1 (1.10.0 available)
  test_api 0.4.16 (0.5.1 available)
  win32 3.1.4 (4.1.3 available)
Changed 5 dependencies!
```
