### ISSUE TITLE
iOS 16: First time `FlutterBluePlus.instance.isOn` goes to False, even though Bluetooth is enabled

### ISSUE THREAD

**Issue by ma2yama** [boskokg/flutter_blue_plus#286]
I'm calling `isOn` to see if Bluetooth is enabled, but the first time `isOn` goes to False, even though Bluetooth is enabled.
Is there any way to solve this problem?

**Comment by chipweinberger** [comment]
please open a PR if you fix the problem

**Comment by baterdene-ums** [comment]
I had the same problem

**Comment by bataa07** [comment]
I had the same problem

**Comment by ma2yama** [comment]
I worked around the problem by sandwiching sleep as follows:

```dart
Future<bool> blueIsOn() async {
  final isOn = await _flutterBlue.isOn;
  if (isOn) return true;

  sleep(const Duration(milliseconds: 100));
  return await _flutterBlue.isOn;
}
```

**Comment by chipweinberger** [comment]
please try 1.7.6+, reopen a new issue if you still have problems.

**Comment by meynety** [comment]
Still having the same issue with `1.12.8` !

**Comment by chipweinberger** [comment]
`isOn` is deprecated in 1.12.9

so try master branch

```
dependencies:
  flutter_blue_plus:
    git:
      url: https://github.com/boskokg/flutter_blue_plus.git
      ref: master
```
